when:
  - event: cron
    cron: build-odoo
  - event: manual

steps:
  - name: clone-enterprise
    image: alpine/git
    commands:
      - mkdir -p ~/.ssh
      - echo "$${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - git clone -b 19.0 --depth=1 git@github.com:odoo/enterprise.git applications/odoo/enterprise
      - printf '19.0\n19.0-%s\nlatest\n19.0-%s\n' "${CI_PIPELINE_NUMBER}" "$(date +%Y%m%d)" > .tags
    environment:
      SSH_PRIVATE_KEY:
        from_secret: ssh_private_key

  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    depends_on:
      - clone-enterprise
    settings:
      repo: d0988b9d-40d5-4591-ab41-d003087a16b7.apps.xaralyn.com/odoo
      registry: d0988b9d-40d5-4591-ab41-d003087a16b7.apps.xaralyn.com
      dockerfile: applications/odoo/Dockerfile
      context: applications/odoo
      platforms: linux/amd64
      tags_file: .tags
      username:
        from_secret: zot_username
      password:
        from_secret: zot_password
